### ISSUE TITLE
Nvim keep crashing if scrolled down

### ISSUE THREAD

**Issue by ksajan** [abzcoding/lvim#114]
When I try to scroll down the using mouse/touchpad and sometimes `G`. It crashes for me. And prints out weird characters on the terminal after that `65;134;45M65;134;45M65;134;45M65;134;45M65;134;45M`. I am not sure whether it's a problem with my terminal (`iterm2`) or because of the configuration/plugin. I am attaching a video below for reference. Thank you for the help!

https://user-images.githubusercontent.com/31013555/212249214-a9b099f5-d9e9-4ac0-b811-e27012303747.mov

<img width="1800" alt="Screenshot 2023-01-13 at 12 03 57 PM" src="https://user-images.githubusercontent.com/31013555/212253657-c4c21caf-52f0-41a4-9a75-fe5b9a90fb21.png">

I have tried waiting for the files to be loaded but still when scrolling down it results in the same.

**Comment by abzcoding** [comment]
Can you check `~/.local/state/nvim/*.log` and `~/.cache/lvim/*.log` for meaningful logs?

Since segfault errors usually happen because of neovim itself, you should check your neovim version.

**Comment by williamgoulois** [comment]
@abzcoding I have this issue for quite a long time (few months i would say)
It is triggered by scrolling with vim horizontal keys `j` and `k` and also `[` `]` (maybe other motions). 

Here is an example where i just hold letter `k` :
https://user-images.githubusercontent.com/37271970/212501759-bd0c2eff-8e29-4811-ad14-8ee284f0bf9f.mov

### Some more information :

Terminal : I use Iterm2 (with tmux) but have the same issue in Alacritty without tmux (so it should come from neovim)

Neovim : NVIM v0.9.0-dev-687+g8b86cb8f5-dirty (Almost HEAD and did not work since few months)

Lunarvim : Latest commit [fix(breadcrumbs): refresh on TabEnter](https://github.com/LunarVim/LunarVim/commit/ea9b648a52de652a972471083f1e1d67f03305fa)

Lvim : My own config https://github.com/williamgoulois/lvim (just one commit from your upstream is important https://github.com/williamgoulois/lvim/commit/b711c47287250250ad2b6bda6ae520e537fc757f the other one is just some java stuff).
I tested with yours and I had the same issue.

Plugins : I saw that with `cinnamon` (or `neoscroll`) this issue is happening more often and easily so i disabled it. Maybe

**Comment by williamgoulois** [comment]
If that helps here is a graphical bug in my tmux window bar after I trigger the scrolling bug with `k`. The window has the bug if i focus the bugged tab before switching, otherwise nothing 🤷 

See video below :

https://user-images.githubusercontent.com/37271970/212502466-630e7cd2-8f8d-423d-b215-02a56ab3f6f1.mov

I have a similar issue if i try to scroll with my trackpad and it happens very quickly. It triggers the same error in my `~/.local/state/nvim/log`. Dunno if it is exactly the same but It exists nvim

**Comment by williamgoulois** [comment]
I do not have this bug when I use (https://github.com/LunarVim/nvim-basic-ide) so I think it comes from our config or lunarvim but not neovim itself

**Comment by luxus** [comment]
this happens randomly with other configs too at the moment, try a stable release and check if you can reproduce

**Comment by williamgoulois** [comment]
> this happens randomly with other configs too at the moment, try a stable release and check if you can reproduce

What do you mean other configs ? Can you link an issue with someone else ? Or have you experience it yourself ?
I just tried with neovim stable (0.8.2) and could not reproduce this bug ! I will stay on this version until we/neovim find how to fix this.

Maybe we could try to do a bisect of our plugins to see if there is one culprit ? 🤔 Because it is strange that i have this with our config but not nvim-basic-ide, the only difference is config/plugins

**Comment by luxus** [comment]
there are some bugs..
one i remember is noice.. have you enabled? noice makes neovim crashes on 0.9 at the moment.
end yes I remember it by myself

**Comment by abzcoding** [comment]
@williamgoulois, you might be unto something. The natural scrolling plugins could very well cause this issue

@ksajan, can you try disabling them?

https://github.com/abzcoding/lvim/blob/31ae8224d3e6b88436e7731333e8687e1f407dcf/lua/user/custom_user.lua#L37

**Comment by abzcoding** [comment]
> 

yeah I have `noice` disabled as well

**Comment by abzcoding** [comment]
> there are some bugs..
> one I remember is noice.. have you enabled it? noice makes neovim crashes on 0.9 at the moment.
> end yes I experienced it by myself

yeah I have `noice` disabled as well

**Comment by Uzaaft** [comment]
> there are some bugs..
> one I remember is noice.. have you enabled it? noice makes neovim crashes on 0.9 at the moment.
> end yes I experienced it by myself

I don't experience this myself, using noice with the nightly. See screenshot for version info. 
![image](https://user-images.githubusercontent.com/48220549/212535524-8898c75e-6aa7-4ab1-abb7-e9274ad6bf73.png)

**Comment by Uzaaft** [comment]
Seems like the noice + nvim nightly issue is fixed in noice.nvim with release 1.7.0

**Comment by luxus** [comment]
noice

**Comment by ksajan** [comment]
> @williamgoulois, you might be unto something. The natural scrolling plugins could very well cause this issue
> 
> @ksajan, can you try disabling them?
> 
> https://github.com/abzcoding/lvim/blob/31ae8224d3e6b88436e7731333e8687e1f407dcf/lua/user/custom_user.lua#L37

I am sorry I was away this week. Give me some time I will test it and let you know.

**Comment by ksajan** [comment]
After disabling it. It still crashes but I don't see those characters like previously.

**Comment by ksajan** [comment]
> there are some bugs.. one I remember is noice.. have you enabled it? noice makes neovim crashes on 0.9 at the moment. end yes I experienced it by myself

No, I tried with both enabling and disabling noice it was the same result.

**Comment by ksajan** [comment]
I think it's the issue with nvim v0.9 itself. I tried a fresh install of your config on other machines intel+M1 macs and arch with different nvim versions. The v0.9 was crashing without any changes in your config and even if I disabled the smooth_scroll. But when I tried the stable release I wasn't able to recreate this issue. I will check more and update here.

**Comment by williamgoulois** [comment]
> I think it's the issue with nvim v0.9 itself.

I came up to the same conclusion everything works fine in nvim stable (0.8.2) so I downgraded

**Comment by abzcoding** [comment]
I'm on this version 

```
NVIM v0.9.0-dev-771+g18fb669b9
Build type: Release
LuaJIT 2.1.0-beta3
```

and it seems to be fine

but yeah using nvim stable is probably the better idea

**Comment by ksajan** [comment]
> I'm on this version
> 
> ```
> NVIM v0.9.0-dev-771+g18fb669b9
> Build type: Release
> LuaJIT 2.1.0-beta3
> ```
> 
> and it seems to be fine
> 
> but yeah using nvim stable is probably the better idea

I was also on this version on my mac m1 and it was giving this bug.

**Comment by abzcoding** [comment]
> I was also on this version on my mac m1 and it was giving this bug.

so the only difference between us is that I'm on a intel mac and you're on a m1 mac 🤔

**Comment by ksajan** [comment]
I do have m1 mac and intel both. I will try the same config on both of them and try to check. I am very new to this so I don't know if I will be able to help much. Thanks for the help!

**Comment by ksajan** [comment]
I think it's the mac itself. I have tried both of them with nightly nvim. @williamgoulois are you using a mac as well ? When I tested the intel one is stable whereas m1 is unstable and crashes when scrolled. 
I have also tried disabling all plugins and then enabling them one by one to check if the cause is any plugins but could find one. 
How can we solve this issue apart from downgrading nvim?

**Comment by luxus** [comment]
neovim 0.9 will be released on the end of the month.
i don't have any crashes with the latest nightly, noice, mini.animate on a m1 pro

**Comment by soerenmartius** [comment]
Just FYI, I am experiencing the same issue after pulling the latest changed

**Comment by abzcoding** [comment]
Closing due to inactivity. Feel free to reopen it
