### ISSUE TITLE
catppuccin is broken due to the rewrite with palettes

### ISSUE THREAD

**Issue by luxus** [abzcoding/lvim#69]
the theme had a big rewrite because it supports palettes now.
cannot load it anymore :(

**Comment by abzcoding** [comment]
fixed via https://github.com/abzcoding/lvim/commit/040a3274a288d1b71bef3c8324d41aa39d81fe2c

**Comment by luxus** [comment]
have you tried it?
space s c and when i select catppuccin i get this. all other themes are working 
```
E5108: Error executing lua .../start/telescope.nvim/lua/telescope/builtin/internal.lua:973: Vim(lua):E5108: Error executing lua ...ack/packer/opt/catppuccin/lua/catp
puccin/core/mapper.lua:219: module 'catppuccin.core.palettes.init' not found:
        no field package.preload['catppuccin.core.palettes.init']
        no file '/nix/store/2i8966gpj3b464mlar7lp4hnpynb6f5n-luajit-2.1.0-2022-04-05-env/share/lua/5.1/catppuccin/core/palettes/init.lua'
        no file '/nix/store/2i8966gpj3b464mlar7lp4hnpynb6f5n-luajit-2.1.0-2022-04-05-env/share/lua/5.1/catppuccin/core/palettes/init/init.lua'
        no file '/Users/luxus/.cache/lvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/catppuccin/core/palettes/init.lua'
        no file '/Users/luxus/.cache/lvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/catppuccin/core/palettes/init/init.lua'
        no file '/Users/luxus/.cache/lvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/catppuccin/core/palettes/init.lua'
        no file '/Users/luxus/.cache/lvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/catppuccin/core/palettes/init/init.lua'
        no file '/nix/store/2i8966gpj3b464mlar7lp4hnpynb6f5n-luajit-2.1.0-2022-04-05-env/lib/lua/5.1/catppuccin/core/palettes/init.so'
        no file '/Users/luxus/.cache/lvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/catppuccin/core/palettes/init.so'
        no file '/nix/store/2i8966gpj3b464mlar7lp4hnpynb6f5n-luajit-2.1.0-2022-04-05-env/lib/lua/5.1/catppuccin.so'
        no file '/Users/luxus/.cache/lvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/catppuccin.so'
stack traceback:
        [C]: in function 'require'
        ...ack/packer/opt/catppuccin/lua/catppuccin/core/mapper.lua:219: in function 'apply'
        .../site/pack/packer/opt/catppuccin/lua/catppuccin/main.lua:18: in function 'load'
        .../site/pack/packer/opt/catppuccin/lua/catppuccin/main.lua:30: in function 'main'
        .../site/pack/packer/opt/catppuccin/lua/catppuccin/init.lua:4: in function 'load'
        [string ":lua"]:1: in main chunk
        [C]: in function 'cmd'
        .../start/telescope.nvim/lua/telescope/builtin/internal.lua:973: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'select_default'
        /Users/luxus/.config/lvim/lua/user/telescope.lua:13: in function '_multiopen'
        /Users/luxus/.config/lvim/lua/user/telescope.lua:44: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:242: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
stack traceback:
        [C]: in function 'cmd'
        .../start/telescope.nvim/lua/telescope/builtin/internal.lua:973: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'select_default'
        /Users/luxus/.config/lvim/lua/user/telescope.lua:13: in function '_multiopen'
        /Users/luxus/.config/lvim/lua/user/telescope.lua:44: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:242: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
```

**Comment by abzcoding** [comment]
@luxus if you want to dynamically load `catpuccin` using `<leader>sc` , you need to make sure that it is loaded and configured already, therefore you would need these changes
```diff
diff --git a/lua/user/plugins.lua b/lua/user/plugins.lua
index 929bb1c..a818350 100644
--- a/lua/user/plugins.lua
+++ b/lua/user/plugins.lua
@@ -38,11 +38,12 @@ M.config = function()
       end,
       config = function()
         require("user.theme").catppuccin()
-        vim.cmd [[colorscheme catppuccin]]
+        -- vim.cmd [[colorscheme catppuccin]]
       end,
       cond = function()
-        local _time = os.date "*t"
-        return (_time.hour >= 17 and _time.hour < 21) and lvim.builtin.time_based_themes
+        return true
+        -- local _time = os.date "*t"
+        -- return (_time.hour >= 17 and _time.hour < 21) and lvim.builtin.time_based_themes
       end,
     },
     {
```

otherwise, it would only work between 17 and 21

**Comment by luxus** [comment]
thank, i was irritated because this only happened with cappuccin

**Comment by luxus** [comment]
i still not get it working as a main theme 
https://github.com/luxus/lvim/commit/8c3459675b223b2411cbae88508af4367cdcccd3

**Comment by thinkryan** [comment]
@luxus For me I have this in my catpuccin() within theme.lua and it's loading up for me. Possibly you can see if this works for you as well.

```
M.catppuccin = function()
  local catppuccin = require "catppuccin"
  catppuccin.setup {
    transparent_background = true,
    dim_inactive = {
      enabled = true,
      shade = "dark",
      percentage = 0.25,
    },
    term_colors = false,
    styles = {
      comments = { "italic" },
      keywords = { "italic" },
      loops = { "bold" },
      types = { "bold" },
    },
    integrations = {
      lsp_trouble = true,
      lspsaga = true,
      nvimtree = {
        enabled = true,
        transparent_panel = true,
      },
      which_key = true,
      lightspeed = lvim.builtin.motion_provider == "lightspeed",
      hop = lvim.builtin.motion_provider == "hop",
      notify = true,
      navic = true,
      ts_rainbow = true,
    },
  }
end

```

Using newer formatting, you can comment out the extensions you don't need

Inside of plugin:

```
    {
      "catppuccin/nvim",
      as = "catppuccin",
      config = function()
        require("user.theme").catppuccin()
      end,
    },

```

Then for lvim configuration on theme setting in config.lua

`lvim.colorscheme = "catppuccin"`
